# Generated by Django 4.2 on 2026-05-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_veterinaria', '0002_alter_mascota_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completada')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
