# Generated by Django 4.2 on 2026-05-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_veterinaria', '0003_historiaclinica_estado_historiaclinica_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completada'), ('X', 'Cancelada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
