# Generated by Django 4.2 on 2026-05-20 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('gestion_veterinaria', '0004_alter_dueño_id_alter_historiaclinica_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TJ', 'Tarjeta de Débito/Crédito'), ('TF', 'Transferencia')], default='EF', max_length=2)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente de Pago'), ('PA', 'Pagado'), ('AN', 'Anulada')], default='PE', max_length=2)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='gestion_veterinaria.historiaclinica')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Factura de Consultas',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_historico', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pagos.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto')),
            ],
        ),
    ]
