# Generated by Django 4.2.30 on 2026-05-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('gestion_veterinaria', '0004_alter_dueño_id_alter_historiaclinica_estado_and_more'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='gestion_veterinaria.historiaclinica'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente de Pago'), ('PA', 'Pagado'), ('CA', 'Cancelado')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('TD', 'Tarjeta de Débito'), ('TC', 'Tarjeta de Crédito'), ('MP', 'Mercado Pago')], max_length=2, null=True),
        ),
    ]
