# Generated by Django 4.2 on 2026-06-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_factura_options_alter_detallefactura_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('TD', 'Tarjeta de Débito'), ('TC', 'Tarjeta de Crédito'), ('TF', 'Transferencia')], max_length=2, null=True),
        ),
    ]
