# Generated by Django 4.2 on 2026-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('MED', 'Medicamento'), ('VAC', 'Vacuna'), ('INS', 'Insumo Clínico'), ('HON', 'Honorarios / Servicios')], default='MED', max_length=3)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True, help_text='Permite desactivar un producto sin borrar su historial')),
            ],
            options={
                'verbose_name': 'Producto / Servicio',
                'verbose_name_plural': 'Productos y Servicios',
            },
        ),
    ]
